-   id: dclint
    name: dclint
    description: 'Validate and enforce best practices in Docker Compose files.'
    entry: dclint
    language: node
    'files': (docker-)?compose\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["dclint@1.0.7"]
    minimum_pre_commit_version: '0'
