# Adapted from https://github.com/pre-commit/mirrors-prettier
name: main
on:
  push:
    branches: [main]
  schedule:
    - cron: '15 8 * * *'
  workflow_dispatch:

jobs:
  build:
    name: main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - run: pip install pre-commit-mirror-maker
    - run: git config --global user.name 'Github Actions'
    - run: git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
    - run: >-
        pre-commit-mirror .
        --language node
        --package-name=dclint
        --entry=dclint
        --description='Validate and enforce best practices in Docker Compose files.'
        --files-regex '(docker-)?compose\.ya?ml$'
        --id=dclint
    - run: |
        git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY
        git push origin HEAD:refs/heads/main --tags
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
